# Generated by Django 6.1 on 2026-08-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
    ]
