# Generated by Django 6.1 on 2026-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0002_user_monthly_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('250ml', '250 ml'), ('300ml', '300 ml'), ('330ml', '330 ml'), ('500ml', '500 ml'), ('600ml', '600 ml'), ('750ml', '750 ml'), ('1L', '1 L'), ('1.25L', '1.25 L'), ('1.5L', '1.5 L'), ('2L', '2 L'), ('2.25L', '2.25 L')], default='500ml', max_length=20),
        ),
    ]
