# Generated by Django 6.1 on 2026-08-26 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0003_orderitem_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount',
            new_name='discount_value',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='tax_value',
        ),
        migrations.AddField(
            model_name='order',
            name='calculated_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='calculated_tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('rs', '₹ (Rupees)'), ('percent', '% (Percentage)')], default='rs', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_type',
            field=models.CharField(choices=[('rs', '₹ (Rupees)'), ('percent', '% (Percentage)')], default='percent', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('250ml', '250 ml'), ('300ml', '300 ml'), ('330ml', '330 ml'), ('450ml', '450 ml'), ('500ml', '500 ml'), ('600ml', '600 ml'), ('750ml', '750 ml'), ('1L', '1 L'), ('1.25L', '1.25 L'), ('1.5L', '1.5 L'), ('2L', '2 L'), ('2.25L', '2.25 L')], default='500ml', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='ShopZee_App.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
