# Generated by Django 6.1 on 2026-08-26 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0004_rename_discount_order_discount_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail', to='ShopZee_App.order'),
        ),
    ]
