# Generated by Django 6.1 on 2026-08-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0005_alter_payment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('ready_for_delivery', 'Ready for Delivery'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='placed', max_length=30),
        ),
    ]
