# Generated by Django 6.1 on 2026-09-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0007_alter_order_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='area_name',
        ),
        migrations.AddField(
            model_name='route',
            name='shop_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
