# Generated by Django 6.1 on 2026-09-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0008_rename_name_route_area_name_route_shop_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='area_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='route',
            name='shop_address',
        ),
    ]
