# Generated by Django 6.1 on 2026-09-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0011_rename_area_name_route_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
    ]
