# Generated by Django 6.1 on 2026-09-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZee_App', '0012_remove_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
